---
- name: Install Libreswan package
  yum:
    name: libreswan
    update_cache: yes
  become: yes
  delegate_to: responder

- name: Start IPSEC service
  systemd:
    name: ipsec
    state: started
    enabled: yes
  become: yes
  delegate_to: responder

- name: Push Libreswan configuration file to responder
  template:
    src: cloud_vpn/providers/rhel/responder/{{ cloud_vpn_initiator_provider }}/configure_static.j2
    dest: /etc/ipsec.d/{{ cloud_vpn_name }}.conf
  become: yes
  delegate_to: responder

- name: Push Libreswan secrets file to responder
  template:
    src: cloud_vpn/providers/rhel/responder/{{ cloud_vpn_initiator_provider }}/configure_psk.j2
    dest: /etc/ipsec.d/ipsec.secrets
  become: yes
  delegate_to: responder

- name: Restart IPSEC service
  systemd:
    name: ipsec
    state: restarted
  become: yes
  delegate_to: responder
