---
- name: Install Libreswan package
  yum:
    name: libreswan
    update_cache: yes
  become: yes
  delegate_to: initiator

- name: Start IPSEC service
  systemd:
    name: ipsec
    state: started
    enabled: yes
  become: yes
  delegate_to: initiator

- name: Push Libreswan configuration file to initiator
  template:
    src: cloud_vpn/providers/rhel/initiator/{{ cloud_vpn_responder_provider }}/configure_static.j2
    dest: /etc/ipsec.d/{{ cloud_vpn_name }}.conf
  become: yes
  delegate_to: initiator

- name: Push Libreswan secrets file to initiator
  template:
    src: cloud_vpn/providers/rhel/initiator/{{ cloud_vpn_responder_provider }}/configure_psk.j2
    dest: /etc/ipsec.d/ipsec.secrets
  become: yes
  delegate_to: initiator

- name: Restart IPSEC service
  systemd:
    name: ipsec
    state: restarted
  become: yes
  delegate_to: initiator
